import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import Blog_card from '../components/blog_card';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Blog_card />
      <a style={{color:'blue'}} href="http://localhost:3000/about">Go to about page</a>
      </main>
    </>
  )
}
